name: Parse HTML and Create Pull Request

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  parse-and-save:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Parse HTML and save content
        run: |
          python -c '
          import requests
          from bs4 import BeautifulSoup

          url = "https://docs.qq.com/doc/DVWlwUWtWZmJkRm5u"
          response = requests.get(url)
          soup = BeautifulSoup(response.text, "html.parser")

          title_element = soup.find("title")
          content_element = soup.find("div", {"class": "doc-content"})

          title = title_element.text.strip() if title_element else "Title not found"
          content = content_element.text.strip() if content_element else "Content not found"

          with open("parsed_content.txt", "w") as f:
              f.write(f"Title: {title}\n")
              f.write(f"Content: {content}\n")
          '

      - name: Create new branch
        run: |
          git checkout -b new-branch

      - name: Make changes and commit
        run: |
          git add parsed_content.txt
          git commit -m "Save parsed content" || echo "No changes to commit"

      - name: Push changes to remote repository
        run: |
          git push origin new-branch

      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Save parsed content
          branch: new-branch
          base: main
          title: Save parsed content
          body: This pull request is created by GitHub Actions to save the parsed content.