name: Parse HTML with Selenium

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  parse-and-save:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install selenium beautifulsoup4
          python -m webdriver_manager.chrome

      - name: Parse HTML and save content
        run: |
          from selenium import webdriver
          from selenium.webdriver.common.by import By
          from selenium.webdriver.chrome.service import Service
          from webdriver_manager.chrome import ChromeDriverManager
          from bs4 import BeautifulSoup
          import time

          url = "https://docs.qq.com/doc/DTnJiakR6YXR5YXZp"

          # 设置ChromeDriver
          service = Service(ChromeDriverManager().install())
          driver = webdriver.Chrome(service=service)

          # 打开网页
          driver.get(url)

          # 等待页面加载
          time.sleep(5)  # 等待5秒，确保页面完全加载

          # 获取页面源码
          html = driver.page_source

          # 解析HTML
          soup = BeautifulSoup(html, "html.parser")

          # 检查标题
          title_element = soup.find("title")
          title = title_element.text.strip() if title_element else "Title not found"

          # 检查内容
          content_element = soup.find("div", {"class": "doc-content"})
          content = content_element.text.strip() if content_element else "Content not found"

          with open("parsed_content.txt", "w") as f:
              f.write(f"Title: {title}\n")
              f.write(f"Content: {content}\n")

          # 关闭浏览器
          driver.quit()

      - name: Create new branch
        run: |
          git checkout -b new-branch

      - name: Make changes and commit
        run: |
          git add parsed_content.txt
          git commit -m "Save parsed content" || echo "No changes to commit"

      - name: Push changes to remote repository
        run: |
          git push origin new-branch

      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Save parsed content
          branch: new-branch
          base: main
          title: Save parsed content
          body: This pull request is created by GitHub Actions to save the parsed content.