name: Parse HTML with Selenium

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  parse-and-save:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Fetch content from Tencent Doc
        run: |
          python -c '
          import requests
          import json
          content_url = "https://docs.qq.com/doc/DTnJiakR6YXR5YXZp"
          headers = {
              "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36",
              "Referer": "https://docs.qq.com/doc/DTnJiakR6YXR5YXZp"
          }
          response = requests.get(content_url, headers=headers)
          response.raise_for_status()
          content = response.json()
          document_content = content["data"]["content"]
          with open("outputText.txt", "w") as file:
              file.write(document_content)
          '

      - name: Create new branch
        run: |
          git checkout -b new-branch

      - name: Make changes and commit
        run: |
          git add outputText.txt
          git commit -m "Save parsed content" || echo "No changes to commit"

      - name: Push changes to remote repository
        run: |
          git push origin new-branch

      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Save parsed content
          branch: new-branch
          base: main
          title: Save parsed content
          body: This pull request is created by GitHub Actions to save the parsed content.